name: Update Memory RSS

on:
  push:
    paths:
      - Memory.txt # реагируем только на изменения Memory.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run shuffle and generate
        run: python send_memory.py

      - name: Commit updated Memory.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Memory.xml
          git commit -m "Update Memory.xml via GitHub Action" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

